engine:
  lib: "opensimplex"
  seed: 0
space:
  rank: 2
  aspect: 1
  shape:
    - 720
    - 720
accumulator:
  octaves: 4
  wave:
    amplitude: 1
    frequency: 0.01
    gain: 0.5
    lacunarity: 2
